name: Iris docker test
on:
  workflow_dispatch
permissions:
  contents: write
  pull-requests: write
jobs:
  test_model:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: "3.10.18"
      - uses: iterative/setup-cml@v2
      - name: run unit tests
        run: |
          pip install -r requirements.txt
          gcloud services enable artifactregistry.googleapis.com
          gcloud artifacts repositories create w6draft-repo --repository-format=docker --location=us-central1 --description="Docker repo for ML models in w6draft"
          gcloud auth configure-docker us-central1-docker.pkg.dev
          docker build -t iris_api_w6draft .
      - name: Create CML report
        env:
          REPO_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          touch report.md
          echo "test output" >> report.md
          echo "\`\`\`" >> report.md
          cat test_output.txt >> report.md
          echo "\`\`\`" >> report.md
          echo "metrics from training" >> report.md
          cml comment create --publish report.md
