name: Iris docker test
on:
  workflow_dispatch
permissions:
  contents: write
  pull-requests: write
jobs:
  test_model:
    runs-on: self-hosted
    steps:
      - name: run unit tests
        run: |
          pip install -r requirements.txt
          gcloud config set account 21f1006304may202503@gmail.com
          gcloud config set project demo0321f1006304
          gcloud services enable artifactregistry.googleapis.com
          gcloud artifacts repositories create w6draft-repo --repository-format=docker --location=us-central1 --description="Docker repo for ML models in w6draft"
          gcloud auth configure-docker us-central1-docker.pkg.dev
          docker build -t iris_api_w6draft .
      - name: Create CML report
        env:
          REPO_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          touch report.md
          echo "test output" >> report.md
          echo "\`\`\`" >> report.md
          cat test_output.txt >> report.md
          echo "\`\`\`" >> report.md
          echo "metrics from training" >> report.md
          cml comment create --publish report.md
